const menu = [
	{
		id: 1,
		title: 'smoked-pork with salad',
		category: 'breakfast',
		price: 8.99,
		img: require('./images/item-01.jpeg').default,
		desc: `fall in love and fall healthy with this full-of-flavor breakfast`,
	},
	{
		id: 2,
		title: 'double burger with fries',
		category: 'lunch',
		price: 14.99,
		img: require('./images/item-02.jpeg').default,
		desc: `you get a great burger and we combine it with the perfect fries `,
	},
	{
		id: 3,
		title: 'green-beaf burger',
		category: 'lunch',
		price: 9.99,
		img: require('./images/item-03.jpeg').default,
		desc: `this beauty will bring you the exact amount of happiness you´re expecting`,
	},
	{
		id: 4,
		title: 'veggie toast',
		category: 'breakfast',
		price: 4.99,
		img: require('./images/item-04.jpeg').default,
		desc: `from distance we all can see it is delicious and healthy`,
	},
	{
		id: 5,
		title: 'burger attack',
		category: 'lunch',
		price: 12.99,
		img: require('./images/item-05.jpeg').default,
		desc: `you better prepare your defenses because this is going to be tough`,
	},
	{
		id: 6,
		title: 'orange dream',
		category: 'drinks',
		price: 3.99,
		img: require('./images/item-06.jpeg').default,
		desc: `fresh and relaxing. What else could it be?`,
	},
	{
		id: 7,
		title: 'sea side sandwich',
		category: 'lunch',
		price: 16.99,
		img: require('./images/item-07.jpeg').default,
		desc: `it has been so long since your last encounter with the sea. End it now`,
	},
	{
		id: 8,
		title: 'turkey sandwich',
		category: 'breakfast',
		price: 12.99,
		img: require('./images/item-08.jpeg').default,
		desc: `just like you read it. This is for you`,
	},
	{   
		id: 9,
		title: 'club house',
		category: 'lunch',
		price: 12.99,
		img: require('./images/item-09.jpeg').default,
		desc: `at any time of the day, it will be a great choice`,
	},
	{   
		id: 10,
		title: 'strawberry smoothie',
		category: 'drinks',
		price: 5.99,
		img: require('./images/item-10.jpeg').default,
		desc: `just the right amount of flavor and sweet to melt into your emotions`,
	},
	{
   	id: 11,
		title: 'chicken wrap',
		category: 'breakfast',
		price: 8.99,
		img: require('./images/item-11.jpeg').default,
		desc: `a solid flavor punch right to your palate`,
	},
	{ 
		id: 12,
		title: 'veggie pasta',
		category: 'lunch',
		price: 9.99,
		img: require('./images/item-12.jpeg').default,
		desc: `a perfect green balance to keep you balanced`,
	},
	{ 
		id: 13,
		title: 'citric lucidity',
		category: 'drinks',
		price: 3.99,
		img: require('./images/item-13.jpeg').default,
		desc: `you see it, you order it, you taste it, you love it`,
	},
	{
    	id: 14,
		title: 'deep fries',
		category: 'breakfast',
		price: 4.99,
		img: require('./images/item-14.jpeg').default,
		desc: `it doesn´t exist a single problem this fries can no solve`,
	},
	{
    
		id: 15,
		title: 'veggie egg toast',
		category: 'breakfast',
		price: 5.99,
		img: require('./images/item-15.jpeg').default,
		desc: `start any day full of the power it can provides to your body`,
	},
	{
		id: 16,
		title: 'red transition',
		category: 'drinks',
		price: 3.99,
		img: require('./images/item-16.jpeg').default,
		desc: `a constant flow from now to a great new happiness`,
	},
	{
    
		id: 17,
		title: 'fried chicken',
		category: 'lunch',
		price: 14.99,
		img: require('./images/item-17.jpeg').default,
		desc: `it´s heavy, tasty and available at any day`,
	},
	{
		id: 18,
		title: 'house pizza',
		category: 'lunch',
		price: 11.99,
		img: require('./images/item-18.jpeg').default,
		desc: `we don´t need to describe it any further. This is simply great`,
	},
	{  
		id: 19,
		title: 'veggie mix',
		category: 'breakfast',
		price: 7.99,
		img: require('./images/item-19.jpeg').default,
		desc: `release yourself from all the chains and fears retaining you. You will enjoy it`,
	},
	{  
		id: 20,
		title: 'pork brochette',
		category: 'lunch',
		price: 9.99,
		img: require('./images/item-20.jpeg').default,
		desc: `it is ranked really high on the top ways to eat pork`,
	},
	{
		id: 21,
		title: 'blue stability',
		category: 'drinks',
		price: 7.99,
		img: require('./images/item-21.jpeg').default,
		desc: `gain it, don´t lose it or regain that particular state of stability`,
	},
];

export default menu;
